# Generated by Django 5.1.2 on 2024-11-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
