# Generated by Django 5.1.2 on 2024-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0002_alter_otpmodel_otp_alter_otpmodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
