# Generated by Django 4.2.6 on 2024-11-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='select_site',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
