# Generated by Django 4.2.6 on 2024-11-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0005_userprofile_select_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='select_site',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
