# Generated by Django 4.2.6 on 2024-11-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0007_alter_userprofile_select_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='select_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
